#ifndef HOTLOAD_PLATFORM_POSIX_POSIX_TIME_HH_
#define HOTLOAD_PLATFORM_POSIX_POSIX_TIME_HH_

#define NSEC_PER_SEC 1000000000LL

long long posix_time_nsec();

#endif // HOTLOAD_PLATFORM_POSIX_POSIX_TIME_HH_
